"""initial schema

Revision ID: 01d01a48c42e
Revises: 
Create Date: 2026-03-02 18:22:58.727187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01d01a48c42e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('free', 'admin', name='userrole'), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('onesignal_player_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('loops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('genre', sa.Enum('afrobeat', 'amapiano', 'trap', 'boom_bap', 'lo_fi', 'gospel', 'afrobeat_worship', 'contemporary_worship', 'dancehall', 'afrohouse', 'highlife_gospel', name='genre'), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('tempo_feel', sa.Enum('slow', 'mid', 'fast', name='tempofeel'), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('file_s3_key', sa.String(length=500), nullable=True),
    sa.Column('preview_s3_key', sa.String(length=500), nullable=True),
    sa.Column('aes_key', sa.Text(), nullable=True),
    sa.Column('aes_iv', sa.Text(), nullable=True),
    sa.Column('waveform_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loops_genre'), 'loops', ['genre'], unique=False)
    op.create_index(op.f('ix_loops_slug'), 'loops', ['slug'], unique=True)
    op.create_table('stem_packs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('loop_id', sa.UUID(), nullable=True),
    sa.Column('genre', sa.Enum('afrobeat', 'amapiano', 'trap', 'boom_bap', 'lo_fi', 'gospel', 'afrobeat_worship', 'contemporary_worship', 'dancehall', 'afrohouse', 'highlife_gospel', name='genre'), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['loop_id'], ['loops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stem_packs_genre'), 'stem_packs', ['genre'], unique=False)
    op.create_index(op.f('ix_stem_packs_slug'), 'stem_packs', ['slug'], unique=True)
    op.create_table('purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('loop_id', sa.UUID(), nullable=True),
    sa.Column('stem_pack_id', sa.UUID(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchase_type', sa.Enum('one_time', name='purchasetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loop_id'], ['loops.id'], ),
    sa.ForeignKeyConstraint(['stem_pack_id'], ['stem_packs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_intent_id')
    )
    op.create_index(op.f('ix_purchases_loop_id'), 'purchases', ['loop_id'], unique=False)
    op.create_index(op.f('ix_purchases_stem_pack_id'), 'purchases', ['stem_pack_id'], unique=False)
    op.create_index(op.f('ix_purchases_user_id'), 'purchases', ['user_id'], unique=False)
    op.create_table('stems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stem_pack_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('file_s3_key', sa.String(length=500), nullable=True),
    sa.Column('preview_s3_key', sa.String(length=500), nullable=True),
    sa.Column('aes_key', sa.Text(), nullable=True),
    sa.Column('aes_iv', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stem_pack_id'], ['stem_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('downloads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('loop_id', sa.UUID(), nullable=True),
    sa.Column('stem_id', sa.UUID(), nullable=True),
    sa.Column('download_url', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loop_id'], ['loops.id'], ),
    sa.ForeignKeyConstraint(['stem_id'], ['stems.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downloads_user_id'), 'downloads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_downloads_user_id'), table_name='downloads')
    op.drop_table('downloads')
    op.drop_table('stems')
    op.drop_index(op.f('ix_purchases_user_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_stem_pack_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_loop_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_stem_packs_slug'), table_name='stem_packs')
    op.drop_index(op.f('ix_stem_packs_genre'), table_name='stem_packs')
    op.drop_table('stem_packs')
    op.drop_index(op.f('ix_loops_slug'), table_name='loops')
    op.drop_index(op.f('ix_loops_genre'), table_name='loops')
    op.drop_table('loops')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
